name: CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # enable manual execution

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo "GITHUB_PATH=$GITHUB_PATH"
        echo $CONDA/bin >> $GITHUB_PATH
        echo "GITHUB_PATH=$GITHUB_PATH"
    - name: Install dependencies
      run: |
        conda info
        conda env list
        conda env update --file environment.yml --name user

    - uses: actions/checkout@v2

    - name: Build
      run: |
        echo "TODO..."

