name: CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # enable manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: python-sample
        environment-file: environment.yml

    - name: Conda info
      run: |
        conda info
        conda env list

    - name: Test
      run: |
        pytest -v
